apiVersion: core.oam.dev/v1beta1
kind: Initializer
metadata:
  annotations:
    addons.oam.dev/description: Create namespace for Observability
  name: ns-observability
  namespace: vela-system
spec:
  appTemplate:
    spec:
      components:
      - name: observability
        properties:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: observability
        type: raw
    status:
      rollout:
        batchRollingState: ""
        currentBatch: 0
        lastTargetAppRevision: ""
        rollingState: ""
        upgradedReadyReplicas: 0
        upgradedReplicas: 0
status:
  observedGeneration: 0
