apiVersion: core.oam.dev/v1beta1
kind: Initializer
metadata:
  annotations:
    addons.oam.dev/description: Terraform Controller is a Kubernetes Controller for Terraform.
  name: terraform
  namespace: vela-system
spec:
  appTemplate:
    spec:
      components:
      - name: terraform-controller
        properties:
          chart: ./chart
          repo_url: https://github.com/oam-dev/terraform-controller
          source_type: GitRepo
        type: helm
      - name: terraform-system
        properties:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: terraform-system
        type: raw
    status:
      rollout:
        batchRollingState: ""
        currentBatch: 0
        lastTargetAppRevision: ""
        rollingState: ""
        upgradedReadyReplicas: 0
        upgradedReplicas: 0
  dependsOn:
  - ref:
      apiVersion: core.oam.dev/v1beta1
      kind: Initializer
      name: fluxcd
      namespace: vela-system
status:
  observedGeneration: 0
