apiVersion: core.oam.dev/v1beta1
kind: TraitDefinition
metadata:
  annotations:
    definition.oam.dev/description: "A list of JSON6902 patch to selected target"
  name: kustomize-json-patch
spec:
  schematic:
    cue:
      template: |
        patch: {
        	spec: {
        		patchesJson6902: parameter.patchesJson
        	}
        }

        parameter: {
        	// +usage=A list of JSON6902 patch.
        	patchesJson: [...#jsonPatchItem]
        }

        // +usage=Contains a JSON6902 patch
        #jsonPatchItem: {
        	target: #selector
        	patch: {
        		op:     string
        		path:   string
        		value?: string
        	}
        }

        // +usage=Selector specifies a set of resources
        #selector: {
        	group?:              string
        	version?:            string
        	kind?:               string
        	namespace?:          string
        	name?:               string
        	annotationSelector?: string
        	labelSelector?:      string
        }
