apiVersion: v1
data:
  initializer: |
    apiVersion: core.oam.dev/v1beta1
    kind: Initializer
    metadata:
      annotations:
        addons.oam.dev/description: Kruise is a Kubernetes extended suite for application automations
      name: kruise
      namespace: vela-system
    spec:
      appTemplate:
        spec:
          components:
          - name: kruise
            properties:
              branch: master
              chart: ./charts/kruise/v0.9.0
              repo_url: https://github.com/openkruise/kruise
              source_type: GitRepo
            type: helm-release
        status:
          rollout:
            batchRollingState: ""
            currentBatch: 0
            lastTargetAppRevision: ""
            rollingState: ""
            upgradedReadyReplicas: 0
            upgradedReplicas: 0
      dependsOn:
      - ref:
          apiVersion: core.oam.dev/v1beta1
          kind: Initializer
          name: fluxcd
          namespace: vela-system
    status:
      observedGeneration: 0
kind: ConfigMap
metadata:
  annotations:
    addons.oam.dev/description: Kruise is a Kubernetes extended suite for application automations
  labels:
    addons.oam.dev/type: kruise
  name: kruise
  namespace: {{.Values.systemDefinitionNamespace}}
