name: SDK Test

on:
  push:
    tags:
      - v*
  workflow_dispatch: {}
  pull_request:
    paths:
      - "vela-templates/definitions/**"
      - "pkg/definition/gen_sdk/**"
    branches:
      - master
      - release-*

permissions:
  contents: read

env:
  # Common versions
  GO_VERSION: '1.19'

jobs:
  sdk-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Build CLI
        run: make vela-cli

      - name: Build SDK
        run: bin/vela def gen-api -f vela-templates/definitions/internal/ -o ./kubevela-go-sdk --package=github.com/kubevela-contrib/kubevela-go-sdk

      - name: Validate SDK
        uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5 # v3.4.0
        working-directory: ./kubevela-go-sdk
        with:
          args: --timeout 5m
