name: Timed Task
on:
  schedule:
    - cron: '* * * * *'

permissions:
  contents: read

jobs:
  clean-image:
    runs-on: self-hosted
    steps:
      - name: Cleanup image
        run: docker image prune -f